name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code on pi5
        run: |
          cd ~/pi-dumb2smart-ir && git pull
